services:
  api:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      DB_HOST: postgres
      DB_PORT: 5432
      DB_NAME: app_db
      DB_USER: app_user
      DB_PASSWORD: password
    volumes:
      - .:/app
      - ../database:/app/data

  postgres:
    image: postgres:16
    container_name: project_pg
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: app_db
      POSTGRES_USER: app_user
      POSTGRES_PASSWORD: password
    volumes:
      - pg_data_proj:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U app_user -d app_db"]
      interval: 5s
      timeout: 5s
      retries: 5

  frontend:
    build: ./pickuppicker-ui  # Make sure this points to your React folder
    ports:
      - "5173:5173"
    depends_on:
      - api
    volumes:
      - ./pickuppicker-ui:/app
      # This prevents your local node_modules from overwriting the container's
      - /app/node_modules

volumes:
  pg_data_proj: