services:
  api:
    build: .
    ports:
      - "8080:8080"
    environment:
      - DB_HOST=aws-1-us-east-1.pooler.supabase.com
      - DB_PORT=5432
      - DB_NAME=postgres
      - DB_USER=postgres.byktlotexzhdtyvriqvm
      - DB_PASSWORD=Thaolinh@0106 # Replace with your real Supabase password!